process.env.DATABASE_URL = '<DATABASE_URL>';
process.env.AWS_ACCESS_KEY_ID = '<AWS_ACCESS_KEY_ID>';
process.env.AWS_SECRET_ACCESS_KEY = '<AWS_SECRET_ACCESS_KEY>';
process.env.KAFKA_CLIENT_CERT = '<KAFKA_CLIENT_CERT>';
process.env.KAFKA_CLIENT_CERT_KEY = '<KAFKA_CLIENT_CERT_KEY>';
process.env.KAFKA_PREFIX = '<KAFKA_PREFIX>';
process.env.KAFKA_TRUSTED_CERT = '<KAFKA_TRUSTED_CERT>';
process.env.KAFKA_URL = '<KAFKA_URL>';
